name: PR Check - Python

on:
  pull_request:
    branches:
      - main
    paths:
      - '{{ cookiecutter.__python_package_name }}/**'
      - '.github/actions/build-and-deploy/action.yml'
      - '.github/workflows/python-pr-check.yml'

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        working-directory: "{{ cookiecutter.__python_package_name }}"
        run: uv sync --group dev

      - name: Check code formatting
        working-directory: "{{ cookiecutter.__python_package_name }}"
        run: uv run ruff format --check --diff src/

      - name: Lint code
        working-directory: "{{ cookiecutter.__python_package_name }}"
        run: uv run ruff check src/
