name: PR Check - Scala

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTOR: "{{ '${{ github.actor }}' }}"
      GITHUB_TOKEN: "{{ '${{ secrets.GITHUB_TOKEN }}' }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: sbt
          cache-dependency-path: |
            {{ cookiecutter.__scala_package_name }}/**/*.sbt
            {{ cookiecutter.__scala_package_name }}/project/build.properties
            {{ cookiecutter.__scala_package_name }}/project/plugins.sbt

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Run sbt clean test and compile
        working-directory: "{{ cookiecutter.__scala_package_name }}"
        run: sbt clean compile test